export default {
  FETCHING: 'REQUEST_FETCHING',
  PENDING: 'REQUEST_PENDING',
  TIMEOUT: 'REQUEST_TIMEOUT',
  ERROR: 'REQUEST_ERROR',
  CORSERROR: 'REQUEST_CORS_ERROR',
  SUCCESS: 'REQUEST_SUCCESS',
  COMPLETED: 'REQUEST_COMPLETED'
}
